import { v2 as cloudinary } from "cloudinary";

import { storage } from "@/lib/config/env";
import { ServiceUnavailableError } from "@/lib/core/errors";
import { createLogger } from "@/lib/core/logger";

const logger = createLogger("storage");

/**
 * Cloudinary, configured for *signed* direct-to-cloud uploads.
 *
 * The browser sends the file straight to Cloudinary, so the bytes never pass
 * through a route handler and the 4.5MB serverless body limit does not apply;
 * a PRD exported to PDF with screenshots clears that easily.
 *
 * Unlike the portfolio's unsigned preset, the browser must present a signature
 * generated here from the API secret. The secret stays server-side, and a
 * signature is bound to a folder, a timestamp and an upload mode, so it cannot
 * be replayed to write somewhere else or reused indefinitely.
 */

let configured = false;

function client() {
  if (!storage.isConfigured) {
    throw new ServiceUnavailableError(
      "File uploads aren't available right now. You can send your enquiry without attachments."
    );
  }

  if (!configured) {
    const { cloudName, apiKey, apiSecret } = storage.credentials;
    cloudinary.config({
      cloud_name: cloudName,
      api_key: apiKey,
      api_secret: apiSecret,
      secure: true,
    });
    configured = true;
  }

  return cloudinary;
}

/** Cloudinary splits uploads by resource type; documents are `raw`. */
export type ResourceType = "image" | "raw";

export function resourceTypeFor(contentType: string): ResourceType {
  return contentType.startsWith("image/") ? "image" : "raw";
}

/**
 * How the asset is delivered once uploaded.
 *
 * `authenticated` refuses unsigned requests, so the URL has to be minted with
 * an expiry. That is right for a client's product requirements and wrong for a
 * review photo, which is published on a page anyone can read: an expiring URL
 * there would 401 the moment the expiry passed, and could not be cached by a
 * CDN in the meantime.
 */
export type DeliveryType = "authenticated" | "upload";

export type SignedUploadParams = {
  cloudName: string;
  apiKey: string;
  signature: string;
  timestamp: number;
  folder: string;
  resourceType: ResourceType;
  uploadUrl: string;
  type: DeliveryType;
};

/**
 * Parameters the browser needs to upload one file.
 *
 * The delivery type is the important part. A default Cloudinary upload is
 * served from a permanent public URL: anyone holding it, forever, can read the
 * file. A client's product requirements are not public, so enquiry attachments
 * default to `authenticated`, which refuses unsigned requests and is read back
 * through `signedUrlFor` with an expiry. A review photo passes `upload`,
 * because being publicly readable is the whole point of it.
 */
export function createUploadSignature(params: {
  folder: string;
  resourceType: ResourceType;
  /** Defaults to `authenticated`, the safer of the two. */
  deliveryType?: DeliveryType;
}): SignedUploadParams {
  const api = client();
  const { cloudName, apiKey, apiSecret } = storage.credentials;

  const deliveryType = params.deliveryType ?? "authenticated";
  const timestamp = Math.round(Date.now() / 1000);

  /*
    Every parameter signed here must also be sent by the browser, and the
    browser must send nothing else that Cloudinary signs. A mismatch produces
    "Invalid Signature", so this object and the client's form fields have to be
    kept in step, which is why the client reads them from this same response
    rather than hard-coding them.
  */
  const signature = api.utils.api_sign_request(
    {
      timestamp,
      folder: params.folder,
      type: deliveryType,
    },
    apiSecret
  );

  return {
    cloudName,
    apiKey,
    signature,
    timestamp,
    folder: params.folder,
    resourceType: params.resourceType,
    type: deliveryType,
    uploadUrl: `https://api.cloudinary.com/v1_1/${cloudName}/${params.resourceType}/upload`,
  };
}

/**
 * A time-limited URL for an authenticated asset.
 *
 * Used in notification email so the attachment is one click away, and
 * regenerated by the admin area afterwards. The expiry means a forwarded email
 * stops granting access to the file, which a permanent public URL would not.
 */
export function signedUrlFor(params: {
  publicId: string;
  resourceType: ResourceType;
  expiresInSeconds?: number;
}): string {
  const api = client();

  return api.utils.private_download_url(params.publicId, "", {
    resource_type: params.resourceType,
    type: "authenticated",
    expires_at: Math.round(Date.now() / 1000) + (params.expiresInSeconds ?? 7 * 24 * 60 * 60),
  });
}

/**
 * Confirms an asset really exists and reports what Cloudinary actually stored.
 *
 * The browser tells us what it uploaded, and the browser can lie. Before an
 * attachment is attached to an enquiry, this asks Cloudinary directly, so a
 * fabricated `public_id`, or a size that disagrees with the real object,
 * cannot be recorded as fact.
 */
export async function describeAsset(params: {
  publicId: string;
  resourceType: ResourceType;
  deliveryType?: DeliveryType;
}): Promise<{ bytes: number; format: string; createdAt: string } | null> {
  try {
    const api = client();
    const asset = await api.api.resource(params.publicId, {
      resource_type: params.resourceType,
      /* Has to match how the asset was uploaded: Cloudinary keeps separate
         namespaces per delivery type, so asking for an `upload` asset under
         `authenticated` reports it as missing. */
      type: params.deliveryType ?? "authenticated",
    });

    return {
      bytes: Number(asset.bytes ?? 0),
      format: String(asset.format ?? ""),
      createdAt: String(asset.created_at ?? ""),
    };
  } catch (error) {
    /* A missing asset is an expected answer here, not a fault. */
    logger.warn("could not describe asset", {
      publicId: params.publicId,
      resourceType: params.resourceType,
      reason: error instanceof Error ? error.message : "unknown",
    });
    return null;
  }
}

/** Removes an asset, used when an enquiry is deleted, so files do not orphan. */
export async function destroyAsset(params: {
  publicId: string;
  resourceType: ResourceType;
  deliveryType?: DeliveryType;
}): Promise<boolean> {
  try {
    const api = client();
    const result = await api.uploader.destroy(params.publicId, {
      resource_type: params.resourceType,
      type: params.deliveryType ?? "authenticated",
      invalidate: true,
    });
    return result.result === "ok";
  } catch (error) {
    logger.error("failed to destroy asset", error, { publicId: params.publicId });
    return false;
  }
}

export const isStorageConfigured = () => storage.isConfigured;
